/*
-- Get all procedures and functions on current database.
SELECT ROUTINE_NAME AS NAME
     , ROUTINE_TYPE AS TYPE
     , CREATED AS CREATED
     , LAST_ALTERED AS UPDATED
  FROM INFORMATION_SCHEMA.ROUTINES
 WHERE ROUTINE_NAME NOT LIKE 'sp_%' 
   AND ROUTINE_NAME NOT LIKE 'fn_%' 
*/


/*
-- Gets Parameters of Stored Procedure.
SELECT ORDINAL_POSITION AS NO
     , PARAMETER_NAME AS NAME
	 , DATA_TYPE AS TYPE
	 , PARAMETER_MODE AS MODE
	 , CHARACTER_MAXIMUM_LENGTH AS LENGTH
	 , NUMERIC_PRECISION AS PRECISION
	 , NUMERIC_SCALE AS SCALE
FROM INFORMATION_SCHEMA.PARAMETERS
WHERE SPECIFIC_NAME = 'GetErrorMsg';

*/